# Kør kun dette en gang
install.packages("devtools")
install.packages("dotenv")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("hrbrthemes")
install.packages("viridis")
install.packages("car")
install.packages("afex")
install.packages("ggsignif")
install.packages("ARTool")
install.packages("PlackettLuce")
library(devtools)
install_github("cloudyr/limer")